# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2020 CERN.
# Copyright (C) 2022 Graz University of Technology.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Tests:
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    env:
      CACHE: ${{ matrix.cache-service }}
      EXTRAS: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .[tests,docs]
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh
